name: chatgpt-nodejs-app-ci-cd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./chatgpt-nodejs-app/app
        run: npm install

      - name: Run unit tests and coverage
        working-directory: ./chatgpt-nodejs-app/app
        run: npm test
      
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          args: >
            -Dsonar.projectKey=chatgpt-nodejs-app
            -Dsonar.organization=lfx
            -Dsonar.host.url=http://54.242.49.83:9000
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto created by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Set in the repository secrets

  build-scan-and-push:
    runs-on: ubuntu-latest
    needs: test-and-analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t chatgpt-nodejs-app:latest ./chatgpt-nodejs-app/app
          docker tag chatgpt-nodejs-app:latest ${{ secrets.DOCKER_USERNAME }}/chatgpt-nodejs-app:latest
      